- src/Leanplum.js
- src/VarCache.js
When a user logs out of an app, we need to clear any stale content for the previously logged in user. This adds a method to do that
> E2-1537: add method to clear content

- Gruntfile.js
- README.md
- package.json
- yarn.lock
There were some leftovers after migrating the tests to `jest`.
- Remove obsolete `grunt-mocha-test`
- Remove `nyc` which is no longer needed
- Update `README.md` test coverage section
> chore: remove legacy test leftovers

- package.json
- webpack.config.js
- yarn.lock
After all files were migrated to TypeScript the processing of JS files by Webpack is not needed.
- Exclude JS files from Webpack configuration
- Add typings for `lodash` to avoid errors on imports
> chore: exclude JS processing in Webpack

- src/ArgsBuilder.ts
- test/specs/Leanplum.test.ts
- test/specs/LeanplumInternal.test.ts
- Move tracking tests to `LeanplumInternal.test.ts`.
- Refactor the tests to use mocks instead of request interceptor.
- Add more tests to cover all use cases.
> test: refactor and extend tracking tests

- test/e2e/index.html
- test/e2e/index.js
Adds a session badge to the e2e application. This provides more feedback to the user that a session was not started yet.
Tested on [my instance](https://lp-web-sdk-e2e.gyoshev.now.sh/).
> chore: add session info to e2e app

- test/e2e/index.js
The ServiceWorker path is incorrect when running in GH pages. This PR fixes this by removing the hardcoded path.
> chore: fix serviceworker registration for gh-pages

- src/Leanplum.ts
- src/LeanplumInternal.ts
- src/PushManager.ts
- src/types/public.ts
- test/e2e/index.js
- test/specs/LeanplumInternal.test.ts
- test/specs/PushManager.test.ts
The ServiceWorker API allows scoping service workers to specific paths in the application (e.g. only under `/shop/`, or in Github Pages). Also, the `registerForWebPush` method can be called as a result of an App Inbox message without parameters, which requires parameters to be set beforehand. 
This PR allows setting the parameters for `registerForWebPush` before running the code.
Unit tests.
> feat: setWebPushOptions method

- test/e2e/index.js
The full path should not be used, as this throws an error "This operation is not secure".
> chore: set correct serviceWorker path for gh-pages

- src/LeanplumInbox.ts
- test/specs/LeanplumInbox.test.ts
Some API responses do not return messages -- do not update the message state for them.
> fix: do not set inbox message state to undefined

- src/LeanplumInternal.ts
- test/mocks/internal.ts
- test/specs/LeanplumInternal.test.ts
- Fix error in dev mode.
- Add unit tests for the fix.
- Fix some linting errors.
> fix: error in dev mode

- test/e2e/index.ts
- tsconfig.e2e.json
- Remove unneeded import from E2E website, which was added because of type defs.
> fix: remove unneeded import from E2E website

- test/e2e/index.ts
Prior to this PR, filling out event parameters sends them along with the `advanceToState` call, due to improper wiring.
> chore: use state tracking parameters

- src/Messages.ts
- test/specs/Messages.test.ts
Messages can be limited for a specific user with the `limitUser` limit, and this PR adds support for it.
> fix: honor the limitUser limit

- test/e2e/index.ts
Previewing a Floating Interstitial with default messages crashes rondo, since they are not serialized from the server. This PR prevents this, albeit not showing the message itself.
> chore: do not crash on empty message title

- test/e2e/index.ts
These commits address some issues when showing Floating Interstitials in Rondo Web:
- Hero image is sometimes skewed in preview / live
- Buttons don't show unless their 'show' field is set explicitly to `true`
> chore: handle more floating intersititial cases

- src/LeanplumInternal.ts
- src/types/public.ts
- test/specs/LeanplumInternal.test.ts
Allows handling of `Open URL` actions in user code, replacing the default `window.location.assign` code.
Triggers a preventable `openUrl` event that receives the URL to open. User code looks like:
```ts
Leanplum.on('openUrl', function(e) {
// prevent default open
e.preventDefault();
// open in new tab, or use in client-side router, etc.
window.open(e.url, '_blank');
});
```
> feat: Allow handling Open URL actions in user code

- src/Messages.ts
- test/specs/Messages.test.ts
When starting a new session, message occurrences are not loaded initially, which wipes out the occurrence tracker when a new message occurrence is tracked.
This PR resolves this by loading the message occurrences on `start` calls.
> fix: load message occurrences on start

- src/Messages.ts
- test/specs/Messages.test.ts
Browser vendors have deprecated support for `document.write`, and this pops us as an issue in the JS SDK.
This PR starts using the `srcdoc` attribute, if available, to render Rich IAM.
> fix: do not use document.write if srcdoc is available

- src/LeanplumInbox.ts
- src/types/internal.ts
- src/types/public.ts
- test/specs/LeanplumInbox.test.ts
Customers can define additional data to send along the app inbox message. Alas, this data is not provided through the SDK API.
This PR allows developers to access the defined data object through a `message.data()` method.
> fix: allow access to additional App Inbox data

- src/LeanplumInternal.ts
- src/Messages.ts
- src/types/public.ts
- test/specs/LeanplumInternal.test.ts
Enables automatic handling of the `Register For Push` app function.
If the service worker is not located at `/sw.min.js`, or requires a different scope, these can be set through `Leanplum.setWebPushOptions`. This should have been done before handling a `Register For Push` function:
```js
Leanplum.setWebPushOptions({
serviceWorkerUrl: '/shop/sw.min.js',
scope: '/shop/'
});
```
> feat: handle the 'Register for Push' app function

- src/Messages.ts
- test/specs/Messages.test.ts
Allows messages to trigger a chained 'register for push' function.
> fix: handle chained 'request for push' messages

- src/Messages.ts
- test/specs/Messages.test.ts
When using the Messaging editor, customers can create message chains that are embedded in the message data, rather than using global IDs.
This PR enables support for them.
> feat: Support embedded message chaining

- src/Leanplum.ts
- src/LeanplumInternal.ts
- test/specs/LeanplumInternal.test.ts
Calling `Leanplum.registerForPush()` without parameters throws a JS error if `Leanplum.setWebPushOptions({})` was not called beforehand.
Also, cleanup.
> fix: registerForPush with default options

- src/LeanplumInbox.ts
- test/specs/LeanplumInbox.test.ts
The `response` function in `downloadMessages` is used in case of success and error. When an error happens, this function is sometimes called with null.
> fix: data can be null in the downloadMessages response

- dist/leanplum.d.ts
- src/Leanplum.ts
- src/LeanplumInternal.ts
- test/specs/LeanplumInternal.test.ts
Currently the `locale` parameter is sent along when calling `start()`, but there is no way to avoid it being set to `"(detect)"`
This PR introduces `setLocale` which can be called before `start()`, similarly to what can already be done with `setDeviceName`
> Add `setLocale` method

- src/LeanplumInternal.ts
- test/specs/LeanplumInternal.test.ts
Developer sessions require a `start` call to be able to preview messages correctly.
> fix: ignore session length in dev mode

- src/LeanplumInbox.ts
- src/LeanplumInternal.ts
- src/LeanplumRequest.ts
- src/LocalStorageManager.ts
- src/Messages.ts
- src/PushManager.ts
- src/StorageManager.ts
- src/VarCache.ts
- test/specs/LeanplumInbox.test.ts
- test/specs/LeanplumIntegration.test.ts
- test/specs/LeanplumRequest.test.ts
- test/specs/Messages.test.ts
- test/specs/VarCache.test.ts
Some browsers and add-ons stop the `sessionStorage` API (e.g. when users disable cookies).
This PR adds an in-memory fallback. This way:
- there is no raised exception
- SPAs continue to work optimally
> fix: App Inbox throws a JS error if sessionStorage is not available

- src/Constants.ts
- src/LeanplumInternal.ts
- src/LeanplumRequest.ts
- src/LeanplumSocket.ts
- src/Network.ts
- src/SocketIoClient.ts
- test/mocks/internal.ts
- test/specs/LeanplumInternal.test.ts
- test/specs/LeanplumRequest.test.ts
- test/specs/LeanplumSocket.test.ts
Allows the Leanplum API to change the endpoints that handle traffic dynamically.
- When a request returns `success: false` and the `apiHost` field, the request is retried on the new endpoint
- The updated configuration is persisted on the device and used for all subsequent requests
> feat: enable dynamic API endpoint configuration

- src/Messages.ts
- test/specs/Messages.test.ts
Event parameters tracked through rich in-app messages (e.g. satisfaction survey) have not been passing event parameters. This PR resolves this, by correctly passing them to the API. This allows customers to analyze the results of the satisfaction survey IAM.
LP-12057
> fix: correctly track in-app message event parameters

- src/Messages.ts
- test/specs/Messages.test.ts
- focuses popup iframe when the IAM loads to notify the screen reader that there's a new element that has gained focus
- adds a title to the iframe so that screen readers notify the user about the popup
> fix: improve accessibility of rich in-app messages
